FROM maven:3.9.4-eclipse-temurin-21 as build

WORKDIR /app

COPY pom.xml ./
COPY src ./src

RUN mvn clean install package -DskipTests

FROM openjdk:21-jdk

WORKDIR /app

EXPOSE 8080

COPY --from=build /app/target/projet-0.0.1-SNAPSHOT.jar /app/app.jar

ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV FRONT_END_DOMAIN=${FRONT_END_DOMAIN}
ENV JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
ENV JWT_REFRESH_SECRET=${JWT_ACCESS_SECRET}
ENV ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
ENV REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
